In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

df=pd.read_csv('student_exam_CLEAN.csv')

In [3]:
df.head()

,student_id,study_hours,attendance,prev_score,sleep_hours,tutoring,parent_edu,result
0,1,5.1,78.5,37.2,5.0,1,3,0
1,2,11.5,45.0,93.2,5.7,0,1,1
2,3,9.1,49.7,65.4,5.1,1,3,1
3,4,7.6,93.9,87.9,4.5,0,1,1
4,5,2.7,72.8,52.4,4.7,1,3,0


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# scaler
scaler = StandardScaler()

# features & target
X = df.drop('result', axis=1)
y = df['result']

# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scaling
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Linear Regression Model

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import StandardScaler

In [9]:
model=LinearRegression()
LM=model.fit(X_train,y_train)

In [10]:
y_pred=LM.predict(X_test)

In [13]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)
n = X_test.shape[0]      # number of rows
p = X_test.shape[1]      # number of features

adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print("Adjusted R2:", adj_r2)

MSE: 0.07354347493388784
RMSE: 0.2711890022362408
R2: 0.6990548340301265
Adjusted R2: 0.6332230789742166


### Logistic Regression Model 

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix,accuracy_score

In [19]:
LRM_model=LogisticRegression()

In [21]:
LRM=LRM_model.fit(X_train,y_train)
y_pred=LRM.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [22]:
confusion_matrix(y_test,y_pred)

array([[16,  1],
       [ 0, 23]])

In [23]:
accuracy_score(y_test,y_pred)

0.975

In [24]:
f1_score(y_test,y_pred)

0.9787234042553191

### K Nearest Neighbour 

In [29]:
from sklearn.neighbors import KNeighborsClassifier

knn_model=KNeighborsClassifier(n_neighbors=5)
knn=knn_model.fit(X_train,y_train)
knn_ypred=knn.predict(X_test)

accuracy_score(y_test,knn_ypred)
confusion_matrix(y_test,knn_ypred)

0.9

### NAiveBayes 

In [32]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()
NB=model.fit(X_train,y_train)
NB_pred=NB.predict(X_test)

accuracy_score(y_test, NB_pred)
confusion_matrix(y_test, NB_pred)

array([[14,  3],
       [ 0, 23]])

### Decision Tree 

In [33]:
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()
DTC=model.fit(X_train,y_train)
Dtc_pred=DTC.predict(X_test)
accuracy_score(y_test, Dtc_pred)

0.875

### Support Vector Machine

In [36]:
from sklearn.svm import SVC

model_svm=SVC(kernel='rbf')
svm=model_svm.fit(X_train,y_train)
svm_pred=svm.predict(X_test)

accuracy_score(y_test, svm_pred)

0.95